### ISSUE TITLE
Compatibility with PHP 7.0.0+

### ISSUE THREAD

**Issue by johnpaulensign** [username115/FRCScouting#165]
`mysql_` functions were deprecated in PHP 5.5.0 and removed in PHP 7.0.0.

Most of them were replaced with `mysqli_` save for `mysql_field_name` and `mysql_fetch_field`.

`mysql_field_name` was not implemented with `mysqli` but can be used as follows:
```php
function mysqli_field_name($result, $field_offset)
{   
    $properties = mysqli_fetch_field_direct($result, $field_offset);
    return is_object($properties) ? $properties->name : null;
}
```

`mysql_fetch_field($sql_result,$i)` can be changed from taking two arguments to one: `mysqli_fetch_field($sql_result)`

`$col_type` needs to be changed to be used as follows:
```php
// type 7 = timestamp
if ($col_type->type == 7) {
        $json .= strtotime($cell);
}
// type 1-5 = tinyint,smallint,int,float,double; 246 = decimal
elseif ($col_type->type <= 5 || $col_type->type == 246 ) {
        $json .= $cell;
} else {
        $json .= '"' . $cell . '"';
}
```

I have made a few other changes to the scouting.php to prevent errors, sync properly with new `mysqli` functions, and prevent empty variables from being used.

I'll submit a pull request so you can take a look.

**Comment by johnpaulensign** [comment]
I cannot submit a PR as it says I do not have permission.

**Comment by username115** [comment]
I will look into this this evening, and try to add 7.0 support. Thank you for bringing it to my attention.

**Comment by username115** [comment]
PHP 5.5.0 was released 4 years ago. I think it is probably safe to say that anybody hosting a server for this app should have updated to at least that version by now (hence the deprecation turning to removal), so I plan to make the change in the generation script, rather than try to support both legacy and new php.

**Comment by username115** [comment]
7000751d53bb72d78396c33da7bc2c0b39b5ba3e has an updated server header and updated script for mysqli (untested). I need to find a permanent solution that allows for different configurations.

I would like to avoid adding checks for which libraries exist on the system, due to the complexity of adding that to the script that generates these headers. If anyone else would like to tackle this, be my guest.

In the meantime, the above commit provides the mysqli script as a workaround (this script should work any year, there is nothing version specific in it). The header will also be required, and if the version number has changed, it will need to be updated there.

**Comment by johnpaulensign** [comment]
I updated the code a few days ago and have tested it. It appears to be working with a few devices. If you would like the code, would it be possible to allow me to submit a pull request to the mysqli branch?

**Comment by username115** [comment]
Please do

**Comment by dachaeon** [comment]
I had an issue with the column type portion of the mysqli changes - it is not clear to me why the specified method failed, but this method worked for me:
`$col_type = mysqli_fetch_field_direct($sql_result, $i);`

**Comment by username115** [comment]
This issue has become priority now that our server has finally been updated to PHP 7+

The generator scripts will need to be updated to match. If anyone still uses older PHP, I'll need to have it generate two separate versions of the server source.
